### ISSUE TITLE
Cover the latest changes in the specs such as string/array for path etc.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#13]
Cover the latest changes in the specs such as string/array for path etc.

**Comment by georgeslabreche** [comment]
@roll can we explicitly list these? Looks like this will be the very last issue I will work on so I want to make sure it is 100% clear in case it ends up being an 11th hour thing.

**Comment by roll** [comment]
If you don't have any design/prototypes based on the specs from a few month ago then we could close this issue. So we're OK if we're reading current text of the spec.

**Comment by georgeslabreche** [comment]
@roll I just went through implementing that resource.path feature when developing that resource.iter() method. The array of paths can be an array of local paths or an array of remote paths but not a mix of both. So I think we're good?

**Comment by roll** [comment]
@georgeslabreche 
Can't be mixed. So yes :+1:
