### ISSUE TITLE
Support for multipart resources.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#15]
Support for multipart resources.

**Comment by georgeslabreche** [comment]
@roll this is already supported unless I am missing something?

**Comment by roll** [comment]
@georgeslabreche 
This means having an individual resource split into a few parts:
- data-part1.csv -> headers/row1/row2
- data-part2.csv -> row3/row4/etc

http://frictionlessdata.io/specs/data-resource/#data-in-multiple-files

---

This is the lowest priority feature from specs-v1 from the whole work.

**Comment by georgeslabreche** [comment]
@roll **IteratorChain** saved the day!
https://commons.apache.org/proper/commons-collections/javadocs/api-2.1.1/org/apache/commons/collections/iterators/IteratorChain.html

Is it OK that we have to explicitly set a base path for the Resource object if the datapackage is using relative file paths?

**Comment by roll** [comment]
@georgeslabreche 
Great!

Base path is even a part of the reference - https://github.com/frictionlessdata/implementations#datapackage

I think in Python/JavaScript now we use current directory as a default base path.

**Comment by georgeslabreche** [comment]
@roll so current directory as in the directory where in the file system the library is residing or  the directory where the app using the library is residing? I'm not 100% convinced this is the best approach, with java at least, because of the potential different possibilities where that library will end up. I'm not yet sure which path is retrieved when using something like `System.getProperty("user.dir");` from within the library when it is invoke by some other Main application. Hmm.

**Comment by roll** [comment]
@georgeslabreche 
Can't say for Java but the idea that user has a working directory with e.g. datapackage.json. So instead of pushing him to write something like this `package = Package('descriptor.json`, base_path='.')` other libs just use current working directory.

**Comment by georgeslabreche** [comment]
@roll I will test behaviour in Java to make sure I use the proper way of getting the working directory in a predictable manner.
