### ISSUE TITLE
Support for csv dialects.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#16]
Support for csv dialects.

**Comment by georgeslabreche** [comment]
Pending tableschema-java refactoring:
https://github.com/frictionlessdata/tableschema-java/issues/18

**Comment by iSnow** [comment]
There is now a `Dialect`class with fields for 

- delimiter
- lineTerminator
- quoteChar
- doubleQuote
- escapeChar
- nullSequence
- skipInitialSpace
- commentChar
- header
- caseSensitiveHeader
- csvddfVersion

According to [specification](https://frictionlessdata.io/specs/csv-dialect/index.html#specification). Working on tests now.

**Comment by iSnow** [comment]
Some tests exist, won't do more
