### ISSUE TITLE
Package class constructor should create a instance with template 

### ISSUE THREAD

**Issue by jackyq2015** [frictionlessdata/datapackage-java#21]
The Package() constructor with empty argument should take a template json file and fill in the jsonObject field instead of leave it empty. So user can fill in the value against the key from template instead of creating a blank instance user cannot use.

**Comment by iSnow** [comment]
No-args constructor has been removed as it has led to an invalid package. 

The desired functionality can mostly be achieve by using the `Package(String jsonStringSource, Path basePath, boolean strict)` constructor to read in a "template" datapackage and removing the resources.
