### ISSUE TITLE
datapackage-java and tableschema-java integration

### ISSUE THREAD

**Issue by jackyq2015** [frictionlessdata/datapackage-java#22]
Would like to see the datapackage-java and reference the tableschema-java data model (or vise verse) so user can benefit from both spec/repo.

**Comment by georgeslabreche** [comment]
Seems like this is the same concern as Issue #9.

**Comment by roll** [comment]
@georgeslabreche 
The #9 is closed - shall we close this one too is it's covered?

**Comment by georgeslabreche** [comment]
@roll I believe this Issue can be closed, yes.

**Comment by roll** [comment]
Awesome, thanks!
