### ISSUE TITLE
Implement more thorough testing for resource schema dereferencing with invalid resource schema

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#24]
Putting an invalid resource schema like this one does not trigger a validation exception:
https://github.com/frictionlessdata/datapackage-java/blob/6710fe22ded6674af7699a773a70bff918e7f76c/src/test/resources/fixtures/schema/invalid_population_schema.json

Because the data package schema only checks if resource schema is an object:
https://github.com/frictionlessdata/datapackage-java/blob/6710fe22ded6674af7699a773a70bff918e7f76c/src/main/resources/schemas/data-package.json#L308-L312

Certainly, something is missing here.

**Comment by iSnow** [comment]
A test exists in the "tableschema-java" project in https://github.com/frictionlessdata/tableschema-java/blob/master/src/test/java/io/frictionlessdata/tableschema/schema/SchemaTest.java, method `testReadFromInValidSchemaFileWithStrictValidation`
