### ISSUE TITLE
Document Relations

### ISSUE THREAD

**Issue by timrobertson100** [frictionlessdata/datapackage-java#38]
Can you please document the expected behaviour of `relations` which is referenced in many places, e.g. [here](https://github.com/frictionlessdata/datapackage-java/blob/master/src/main/java/io/frictionlessdata/datapackage/resource/Resource.java#L41)?

I had naively assumed a DP reader would follow foreign keys and return the end of the relation in a nested object inline.

Thanks!

**Comment by iSnow** [comment]
That should be detailed in https://github.com/frictionlessdata/specs which is what we are trying to implement. If that project doesn't have it, the issue should be reported there first

**Comment by iSnow** [comment]
Closing as this is a documentation issue for the specifications, not the Java port.

**Comment by timrobertson100** [comment]
FWIW I think this is a poor response. This is a Java API with public methods that have next to no documentation - linking to the relevant section of the official documentation would be appropriate.

**Comment by iSnow** [comment]
Sorry to hear that but it is what it is. 

The Java port for ages has had basically no contributors except for me and I am an unpaid volunteer. I tried to improve the quality of code and docs where I use the lib, but I don't need or use document relations. If you want to contribute better docs and/or code for this part, I am more than happy to accept pull requests. 

If you want to work on it, I can re-open the issue.
