### ISSUE TITLE
Register project at travis-ci.com, please

### ISSUE THREAD

**Issue by iSnow** [frictionlessdata/datapackage-java#41]
# Overview

@roll we used Travis-CI dot ORG (https://travis-ci.org/frictionlessdata/datapackage-java) as a CI and test pipeline, but that's gone away. Could you please register us at https://www.travis-ci.com/ instead?

TIA

**Comment by roll** [comment]
DONE in https://github.com/frictionlessdata/datapackage-java/pull/42
