### ISSUE TITLE
Support datapackage identifier spec?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-java#5]
# Overview

> This issue is not a part of first iteration of work and created for a future implementation if possible

Specification - http://dataprotocols.org/data-package-identifier/

**Comment by iSnow** [comment]
Link is dead, is this issue still relevant, @roll ?

**Comment by roll** [comment]
@iSnow 
The working link is https://frictionlessdata.io/specs/data-package-identifier/

I'm not sure honestly whether it's mature enough to be implemented. We haven't implemented it in Python/JavaScript libraries yet

**Comment by iSnow** [comment]
Closing till the specs are mature enough for implementation.
