### ISSUE TITLE
Read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#6]
Read and validate a data package descriptor, including profile-specific validation via the registry of JSON Schemas.

- [x] Create package from JSONObject descriptor.
- [x] Create package from JSON String descriptor.
- [x] Create package from Remote File descriptor.
- [x] Create package from Local File descriptor.
- [x] Schema validation.
- [x] Support strict validation flag (GitHub Issue #17).
- [x] Profile-specific validation via the registry of JSON Schemas.

**Comment by georgeslabreche** [comment]
@roll I think the only think missing thing here is was _"Support strict validation flag,"_ which I implemented as as new issue I created, issue #17, and _"Profile-specific validation via the registry of JSON Schemas."_

For _"Read and validate a data package descriptor,"_ I've updated the README to document how this has been implemented.

I'm not exactly sure what is meant by "_Profile-specific validation via the registry of JSON Schemas,"_ even after reviewing the [specs](http://frictionlessdata.io/specs/profiles/). Does it simply mean that the  data under "resources" needs to conform to the given the profile? For instance, if I have `profile:"tabular-data-resource"` then the files assigned to the data property need to be validated as CSV and then that CSV needs to be valid with respect to the provided schema (if a schema is provided in the first place)?

**Comment by roll** [comment]
@georgeslabreche 
Cool. Could you please post an update to https://github.com/frictionlessdata/implementations/issues/26 (requirements I should mark as done)? I think I've reviewed this lib when it was just bootstrapped.

Related to validation:
- a descriptor should conform to JSON Schema pointed in `descriptor.profile` attribute. It could be from the registry - http://frictionlessdata.io/schemas/registry.json. Or an url to JSON Schema. Take a look on https://github.com/frictionlessdata/datapackage-js/blob/master/src/profile.js

**Comment by georgeslabreche** [comment]
@roll I'm bypassing the registry and checking if the profile files exist directly. Is this OK or is there a particular reason why the registry exists and why I should scan it before trying to read the profile file in question?

**Comment by roll** [comment]
@roll
I do the same for other implementations. For now a concept that we sheep profiles with the libraries so on low-level it's enough to check e.g. for `{profile-id}.json` file in `profiles`.

**Comment by georgeslabreche** [comment]
@roll I'll mark this as Done then :).
