### ISSUE TITLE
Create and edit a data package descriptor, including methods to add and remove resources and validation after editing.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#7]
Create and edit a data package descriptor, including methods to add and remove resources and validation after editing.

- [x] Add descriptor String property
- [x] Add descriptor JSONObject property
- [x] Add descriptor JSONArray property
- [x] Remove descriptor property by key name.
- [x] Add JSONObject resources.
- [x] Remove JSONObject resources.
- [x] Validation after editing.

**Comment by georgeslabreche** [comment]
@roll:
1) The _"methods to add and remove resources"_ were already implemented, I have documented this process in the README. However, this is done with JSONObject rather than a Resource class (which doesn't exist right now). Should I implement this with a Resource class instead?

2) For "create and edit a data package descriptor," that's pretty generic and there's a lot of properties so I just implemented the following methods:

```
public void addProperty(String key, String value) throws DataPackageException;
public void addProperty(String key, JSONObject value) throws DataPackageException;
public void addProperty(String key, JSONArray value) throws DataPackageException;
public void removeProperty(String key);
```
Will these suffice?

3) For validation after editing, do we just want to have a "strict" flag for all those addProperty methods that, when set to true, just calls `this.validate()` after adding a property in order to validate the Package instance against the Schema? What if the Package was already invalid before we called addProperty or addResource? Call this.validate() would throw an exception but only because the Package was already invalid to begin with rather than because of the new property that was just added.

**Comment by roll** [comment]
@georgeslabreche 

1. It's hard for me to say what will be better for Java. General recommendation is to be as closer as possible with Python/JavaScript/Ruby API to make knowledge across the eco-system more interchangeable. External API here is not related to having or not `Resource` class in Python/etc. Users operate with just data structures (so I suppose that what you've already implemented with a JSONObject):
```python
package.add_resource({'name': 'name', 'path': 'data.csv'}) # but it returns an instance of a `Resource` class
```

2. In dynamic languages we just allow inline editing of a descriptor and then committing the changes:
```python
package.descriptor['name'] = 'other_name'
package.commit() # here re-validation happening
```

3. So related to the `strict` flag. The logic in Python/JavaScript/etc behind it:
- non strict more (default):
```
package = Package(descriptor) # add validation errors to `package.errors`
package.add_resource(resource_descriptor) # add validation errors to `package.errors`
package.descriptor['name'] = 'other_name'
package.commit() # add validation errors to `package.errors`
...
```
- strict mode:
```
package = Package(descriptor, strict=True) # raise exception with validation errors
package.add_resource(resource_descriptor) # raise exception with validation errors
package.descriptor['name'] = 'other_name'
package.commit() # raise exception with validation errors
...
```
I think this behaviour could be translated very closely to Java.

**Comment by roll** [comment]
So to summarize:
- we validatie a descriptor on every call of:
  - `constructor`
  - `add/removeResource`
  - `add/removeProperty`
- if package is created with no strict flag after every validation we just add validation errors to `package.errors` and set `package.valid` to `False`
- if package is created with `strict=True` after every validation we raise an exception if there are validation errors
