### ISSUE TITLE
Provide an API to interact with a data package descriptor

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#8]
Provide an API to interact with a data package descriptor.

**Comment by georgeslabreche** [comment]
@roll does this suffice?

```
public JSONArray getResources();
public JSONObject getResource(String resourceName);
public Object getProperty(String key);
public Object getPropertyString(String key);
public Object getPropertyJSONObject(String key);
public Object getPropertyJSONArray(String key);
```

**Comment by roll** [comment]
@georgeslabreche 
Will `package.getResources()` return an array of `Resource` instances?

Python/JavaScript API - https://github.com/frictionlessdata/implementations#datapackage

**Comment by georgeslabreche** [comment]
@roll: package.getResources() will return a JSONArray of JSONObjects representing Resource objects. This goes back to my first question in Issue #7. The reason I went ahead with JSONObjects and JSONArray is because its seems like 1) we don't necessarily want to map every single datapackage JSON elements to equivalent class and properties and 2) in the other libraries we are interacting with JSON structure directly so I thought I'd preserve that element. Nothing stops us from creating a Resource class and working with that, but where do we draw the lines as to what is represented by a class and what isn't?

**Comment by roll** [comment]
@georgeslabreche 
In other libs `package.resources` has `Resource[]` type. It's pretty common operation on data package when we iterate over resource and e.g. reading them:

```python
for resource in package.resoures:
  print(resource.read(keyed=True))
```

So providing here API over raw data structures is very desirable.

And for raw data structure iteration users always could do:

```python
for resource_descriptor in package.descriptor.['resoures']:
  print(resource_descriptor)
```

**Comment by georgeslabreche** [comment]
@roll I agree. Will do!
