### ISSUE TITLE
Streaming and reading of resources through a table schema with cast on iteration.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#9]
Streaming and reading of resources through a table schema with cast on iteration.

- [x] Iterate over data in CSV String format.
- [x] Iterate over data in local CSV file.
- [x] Iterate over data in remote CSV file (URL).
- [x] Iterate over data in JSON Array format.
- [x] Cast on iteration.
- [x] Update README.

**Comment by georgeslabreche** [comment]
@roll So we only attempt to cast the data if the schema is provided as part of the Resource object?

**Comment by roll** [comment]
@georgeslabreche 
Yes - https://github.com/frictionlessdata/tableschema-js/blob/master/src/table.js#L55-L143.

In Python/JavaScript a `Resource` class just re-use `tableschema.Table` for all this operations. Hopefully it's possible to do also in Java.

**Comment by georgeslabreche** [comment]
Oh man!

**Comment by georgeslabreche** [comment]
Pending tableschema-java refactoring:
https://github.com/frictionlessdata/tableschema-java/issues/18
